version: '3.1'

services:
  db:
    build: .
    container_name: api-db
    restart: always
    tty: true
    ports:
      - "5433:5432"
    volumes:
      - .docekr/dbdata:/var/lib/postgresql/dbdata
    environment:
      - POSTGRES_PASSWORD=docekr
      - POSTGRES_DB=projectdb
